name: Keep Render Service Alive

on:
  schedule:
    # 매 5분마다 실행 (Render 15분 sleep 방지)
    - cron: '*/5 * * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    steps:
    - name: Ping Render server
      run: |
        echo "[INFO] Pinging Render server to prevent sleep..."
        curl -f -s -o /dev/null -w "HTTP Status: %{http_code}\n" ${{ secrets.RENDER_URL }} || echo "[WARN] Server might be sleeping"
        echo "[OK] Ping completed"
      continue-on-error: true


